# Site settings
title: Amazing Blog Template
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://internetfarmer.github.io/blogTemplate/" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jekyll

# About Page Setting
aboutDescription: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your about page here. You can edit this
  line in _config.yml. 

# Contact Page Setting
twitter_url: http://twitter.com
email: your-email@domain.com
facebook_url: http://facebook.com
linkedin_url: http://linkedin.com
github_url: http://github.com

# Build settings
markdown: kramdown
